const DEFAULT_IGDB_SYNC_LIMIT = 100;
const DEFAULT_IGDB_SYNC_DELAY_MS = 1000;
const DEFAULT_GAMES_SYNC_CONCURRENCY = 5;

const IMAGE_FIELDS = ["cover", "screenshots", "artworks"] as const;

const SINGLE_GAME_QUERY_FIELDS = [
  "name",
  "slug",
  "category",
  "storyline",
  "summary",
  "first_release_date",
  "total_rating",
  "total_rating_count",
  "hypes",
  "updated_at",
  "cover.id",
  "cover.url",
  "screenshots.id",
  "screenshots.url",
  "artworks.id",
  "artworks.url",
  "franchises.id",
  "franchises.name",
  "franchise.id",
  "franchise.name",
  "collections.id",
  "collections.name",
  "videos.id",
  "videos.video_id",
  "alternative_names.id",
  "alternative_names.name",
  "genres.id",
  "genres.name",
  "keywords.id",
  "keywords.name",
  "themes.id",
  "themes.name",
  "game_modes.id",
  "game_modes.name",
  "websites.id",
  "websites.url",
  "platforms",
  "game_type.id",
  "game_type.type",
  "involved_companies.id",
  "involved_companies.company.name",
  "involved_companies.developer",
  "involved_companies.publisher",
  "involved_companies.porting",
  "involved_companies.supporting",
  "release_dates.id",
  "release_dates.date",
  "release_dates.human",
  "release_dates.m",
  "release_dates.y",
  "release_dates.platform",
  "release_dates.release_region",
].join(", ");

const PLATFORM_QUERY_FIELDS = [
  "name",
  "slug",
  "generation",
  "created_at",
  "platform_family.name",
  "platform_family.slug",
  "platform_logo.url",
].join(", ");

const UPDATABLE_GAME_FIELDS = [
  "slug",
  "name",
  "type",
  "storyline",
  "summary",
  "modes",
  "genres",
  "keywords",
  "themes",
  "companies",
  "websites",
  "franchises",
  "videos",
  "alternative_names",
  "first_release",
  "release_dates",
  "platformIds",
  "igdb",
] as const;

const UPDATABLE_PLATFORM_FIELDS = [
  "name",
  "slug",
  "generation",
  "family",
  "logo",
  "raId",
] as const;

export {
  DEFAULT_IGDB_SYNC_LIMIT,
  DEFAULT_IGDB_SYNC_DELAY_MS,
  DEFAULT_GAMES_SYNC_CONCURRENCY,
  SINGLE_GAME_QUERY_FIELDS,
  PLATFORM_QUERY_FIELDS,
  UPDATABLE_GAME_FIELDS,
  IMAGE_FIELDS,
  UPDATABLE_PLATFORM_FIELDS,
};
