const DEFAULT_IGDB_SYNC_LIMIT = 100;
const DEFAULT_IGDB_SYNC_DELAY_MS = 1000;
const DEFAULT_GAMES_SYNC_CONCURRENCY = 5;

const IMAGE_FIELDS = ["cover", "screenshots", "artworks"] as const;

const SINGLE_GAME_QUERY_FIELDS = [
  "name",
  "slug",
  "category",
  "storyline",
  "summary",
  "first_release_date",
  "total_rating",
  "total_rating_count",
  "hypes",
  "updated_at",
  "cover.id",
  "cover.url",
  "screenshots.id",
  "screenshots.url",
  "artworks.id",
  "artworks.url",
  "franchises.id",
  "franchises.name",
  "franchise.id",
  "franchise.name",
  "collections.id",
  "collections.name",
  "videos.id",
  "videos.video_id",
  "alternative_names.id",
  "alternative_names.name",
  "genres.id",
  "genres.name",
  "keywords.id",
  "keywords.name",
  "themes.id",
  "themes.name",
  "game_modes.id",
  "game_modes.name",
  "websites.id",
  "websites.url",
  "platforms",
  "game_type.id",
  "game_type.type",
  "involved_companies.id",
  "involved_companies.company.name",
  "involved_companies.developer",
  "involved_companies.publisher",
  "involved_companies.porting",
  "involved_companies.supporting",
  "release_dates.id",
  "release_dates.date",
  "release_dates.human",
  "release_dates.m",
  "release_dates.y",
  "release_dates.platform",
  "release_dates.release_region",
  "status",
  "version_parent",
  "version_title",
  "parent_game",
  "aggregated_rating",
  "aggregated_rating_count",
  "rating",
  "rating_count",
  "url",
  "game_engines.id",
  "game_engines.name",
  "player_perspectives.id",
  "player_perspectives.name",
  "multiplayer_modes.platform",
  "multiplayer_modes.campaigncoop",
  "multiplayer_modes.dropin",
  "multiplayer_modes.lancoop",
  "multiplayer_modes.offlinecoop",
  "multiplayer_modes.offlinecoopmax",
  "multiplayer_modes.offlinemax",
  "multiplayer_modes.onlinecoop",
  "multiplayer_modes.onlinecoopmax",
  "multiplayer_modes.onlinemax",
  "multiplayer_modes.splitscreen",
  "multiplayer_modes.splitscreenonline",
  "age_ratings.organization.name",
  "age_ratings.rating_category.rating",
  "age_ratings.synopsis",
  "language_supports.language.name",
  "external_games.uid",
  "external_games.url",
  "external_games.external_game_source",
  "dlcs",
  "expansions",
  "standalone_expansions",
  "bundles",
  "expanded_games",
  "forks",
  "ports",
  "remakes",
  "remasters",
  "similar_games",
].join(", ");

const PLATFORM_QUERY_FIELDS = [
  "name",
  "slug",
  "generation",
  "created_at",
  "platform_family.name",
  "platform_family.slug",
  "platform_logo.url",
].join(", ");

const UPDATABLE_GAME_FIELDS = [
  "slug",
  "name",
  "type",
  "storyline",
  "summary",
  "modes",
  "genres",
  "keywords",
  "themes",
  "companies",
  "websites",
  "franchises",
  "videos",
  "alternative_names",
  "first_release",
  "release_dates",
  "platformIds",
  "status",
  "versionTitle",
  "game_engines",
  "player_perspectives",
  "multiplayer_modes",
  "ageRatings",
  "languages",
  "externalStores",
  "igdb",
] as const;

const UPDATABLE_PLATFORM_FIELDS = [
  "name",
  "slug",
  "generation",
  "family",
  "logo",
  "raId",
] as const;

export {
  DEFAULT_IGDB_SYNC_LIMIT,
  DEFAULT_IGDB_SYNC_DELAY_MS,
  DEFAULT_GAMES_SYNC_CONCURRENCY,
  SINGLE_GAME_QUERY_FIELDS,
  PLATFORM_QUERY_FIELDS,
  UPDATABLE_GAME_FIELDS,
  IMAGE_FIELDS,
  UPDATABLE_PLATFORM_FIELDS,
};
